version: '3'
services:
  simulator:
    image: simulator
    labels:
    - traefik.enable=true
    - traefik.http.routers.simulator.rule=Host(`simulator.flight1.dodedodo.com`)
    - traefik.http.routers.simulator.tls=true
    - traefik.http.routers.simulator.tls.certresolver=lets-encrypt
    - traefik.http.services.simulator.loadbalancer.server.port=8080
    networks:
    - web
      