version: '3.5'
services:
  simulator_${user_id}_${sim_no}:
    image: simulator
#    deploy:
#      resources:
#        limits:
#          memory: "2G"
    labels:
    - traefik.enable=true
    - traefik.http.routers.gzweb_${user_id}_${sim_no}.rule=Host(`gz.${user_id}.${sim_no}.flight1.dodedodo.com`)
    - traefik.http.routers.gzweb_${user_id}_${sim_no}.tls=true
    - traefik.http.routers.gzweb_${user_id}_${sim_no}.tls.certresolver=lets-encrypt
    - traefik.http.routers.gzweb_${user_id}_${sim_no}.service=gzweb_service_${user_id}_${sim_no}
    - traefik.http.services.gzweb_service_${user_id}_${sim_no}.loadbalancer.server.port=8080
    - traefik.http.routers.webterminal_${user_id}_${sim_no}.rule=Host(`term.${user_id}.${sim_no}.flight1.dodedodo.com`)
    - traefik.http.routers.webterminal_${user_id}_${sim_no}.tls=true
    - traefik.http.routers.webterminal_${user_id}_${sim_no}.tls.certresolver=lets-encrypt
    - traefik.http.routers.webterminal_${user_id}_${sim_no}.service=webterminal_service_${user_id}_${sim_no}
    - traefik.http.services.webterminal_service_${user_id}_${sim_no}.loadbalancer.server.port=3000    
    tty: true  
    volumes:
    - ./../../ros_packages:/projects
   
networks:
  default:
    name: express-simcloud_web
      
